services:
  backend:
    build: ./backend
    image: karand07/backend:latest
    ports:
      - "5000:3000"  
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network
    restart: always
  frontend1:
    build: ./farmer_frontend
    image: karand07/farmer-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - frontend-network
    restart: always
  frontend2:
    build: ./company_frontend
    image: karand07/company-frontend:latest
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - frontend-network
    restart: always
  frontend3:
    build: ./admin_frontend
    image: karand07/admin-frontend:latest
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - frontend-network
    restart: always

  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network   
    restart: always

volumes:
  mongo-data:

networks:
  backend-network:
  frontend-network: