name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4   # ✅ updated version

      - name: Set up Docker
        run: docker --version

      - name: Build Docker Images
        run: docker compose build